# Site wide configuration

title: #Shruti Palaskar
locale: en_US
url: https://rhtk07.github.io/
# Jekyll configuration
theme: minimal-mistakes-jekyll

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: Rohit K
  avatar:  profile_pic_1.jpg
  position: MTech Signal Processing
  school: Indian Institue of Sciences
  place: Bangalore, India.
  bio: "Graduate student<br/>Language Technologies Institute, School of Computer Science&#13;&#10;Carnegie Mellon University&#13;&#10;Pittsburgh, PA"
  email: rohitk@iisc.ac.in
  disqus-shortname:
  twitter: #sjpal94
  facebook:  #username
  google:
    scholar: https://scholar.google.com/citations?user=4PulMD4AAAAJ&hl=en
    plus:  #username
    analytics: UA-57438847-4
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: RhtK07
  stackoverflow: #username 
  linkedin: Rohit K #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
