# Site wide configuration

title: Rohit K            
locale:           en_US
url: https://rhtk07.github.io/
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

# Site owner
owner:
  name: 
  avatar: rohitk_b1.jpg 
  position: Graduate Student
  school: Johns Hopkins University
  place: Baltimore, Maryland.
  bio: "Graduate student<br/>Electrical and Computer Engineering &#13;&#10; Johns Hopkins University&#13;&#10;Baltimore, Maryland"
  email:  rkumar44@jhu.edu
  disqus-shortname:
  twitter: #username
  facebook:  #username
  google:
    scholar: https://scholar.google.com/citations?user=4PulMD4AAAAJ&hl=en
    plus: 
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: RhtK07
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: www.linkedin.com/in/rohit-k07 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  scholar: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
